permissions:
  contents: write

on:
  push:

jobs:
  job1:
    name: Check py diff
    runs-on: ubuntu-latest
    outputs:
      result: ${{ needs.steps.check-change.outputs.my_changes }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: check-change
        with:
          filters: |
            my_changes:
              - 'folder/**/*.py'

      - name: check output
        env: 
          MYOUTPUT: ${{ steps.check-change.outputs.my_changes }}
        run: echo $MYOUTPUT

  job2:
    name: Output output
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      ANYCHANGE: ${{ needs.changes_job.outputs.result }}

    steps:
      - name: Print my-changes aka. ANYCHANGE
        run: |
          echo "anychange: $ANYCHANGE"
