permissions:
  contents: write

on:
  push:
  workflow_dispatch:
    inputs:
      myboolean:
        required: false
        type: boolean
        default: true
  workflow_call:
    inputs:
      myboolean:
        required: false
        type: boolean
        default: true


jobs:
  changes_job:
    name: Check py changes
    runs-on: ubuntu-latest
    outputs:
      result: ${{ needs.steps.check-change.outputs.my_changes }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: check-change
        with:
          filters: |
            my_changes:
              - 'folder/**/*.py'

      - name: check output
        env: 
          MYOUTPUT: ${{ steps.check-change.outputs.my_changes }}
        run: echo $MYOUTPUT

  test-job:
    name: Test Job
    runs-on: ubuntu-latest
    env:
      ANYCHANGE: ${{ needs.changes_job.outputs.result }}

    steps:
      - uses: actions/checkout@v3

      - name: Print my-changes aka. ANYCHANGE
        run: |
          echo "anychange: $ANYCHANGE"

      - name: Step runs
        id: running-step
        run: echo Hello, world!
      
      - name: Step boolean true
        if: ${{ inputs.myboolean }}
        run: echo runned

      - name: Step fails
        run: echo fails && exit 1
        
      - name: Step always
        if: always()
        run: echo runs always
        
      - name: Step always + outcome.success
        if: ${{ always() && steps.running-step.outcome == 'success' }}
        run: echo runned

      - name: Step always + outcome.failure
        if: ${{ always() && steps.running-step.outcome == 'failure' }}
        run: echo runned
        
      - name: Step !cancelled
        if: ${{ !cancelled() }}
        run: echo runned

      - name: Step !cancelled + outcome.success
        if: ${{ !cancelled() && steps.running-step.outcome == 'success' }}
        run: echo runned
        
      - name: Step !cancelled + outcome.failure
        if: ${{ !cancelled() && steps.running-step.outcome == 'failure' }}
        run: echo runned

      - name: Step myboolean true + !cancelled 
        if: ${{ inputs.myboolean && !cancelled()  }}
        run: echo runned
        
      - name: Step !cancelled + myboolean true
        if: ${{ !cancelled() && inputs.myboolean }}
        run: echo runned

      - name: Step without condition
        run: echo Bye, Bye!
