permissions:
    contents: write
  
on:
  push:

jobs:
  job1:
    name: Check py diff
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.check_change.outputs.my_changes }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: dorny/paths-filter@v3
        id: check_change
        with:
          filters: |
            my_changes:
              - 'folder/**/*.py'

      - name: check output
        env: 
          MYOUTPUT: ${{ steps.check_change.outputs.my_changes }}
        run: echo $MYOUTPUT

  job2:
    name: Output output
    needs: job1
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      ANYCHANGE: ${{ needs.job1.outputs.result }}

    steps:
      - name: if check
        if: ${{ needs.job1.outputs.result == 'false' }}
        run: echo "result is false"

      - name: Print my-changes aka. ANYCHANGE
        run: |
          echo "anychange: $ANYCHANGE"

  job3:
    name: Job 3
    needs: job1
    uses: ./.github/workflows/main.yml
    with:
      myboolean: ${{ needs.job1.outputs.result == 'false' }}
