name: Create PR with CLI

on:
  workflow_dispatch: 

env:
  SOURCE_BRANCH: testbranch
  TARGET_BRANCH: main
  REVIEWER: francesco-esp

jobs:
  my-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        run: |
          PR_TITLE="my title"
          gh pr create --base $TARGET_BRANCH --head $SOURCE_BRANCH \
            --title "$PR_TITLE" --body "" --reviewer "$REVIWER"
        env:
          GITHUB_TOKEN: ${{ github.token }}
